title: Luyen Tran
description: Luyen's Blog
author: Luyen Tran
logo: /blog/static/img/avatar.png
github: https://github.com/luyentm
about: Coder

baseurl: ""
url: "https://luyentm.github.io/blog/"

disqus_shortname: luyentm
google_analytics: UA-98180508-1

share:


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
